replicaCount: ${replica_count}
tls:
  certData: ${cert_data}
  keyData: ${key_data}
  caCertData: ${ca_cert_data}
image:
 repository: images.releases.hashicorp.com
 name: hashicorp/terraform-enterprise
 tag: ${tfe_release}
env:
  variables:
    TFE_HOSTNAME: ${fqdn}
    TFE_DATABASE_HOST: ${pg_address}
    TFE_DATABASE_NAME: ${pg_dbname}
    TFE_DATABASE_USER: ${pg_user}
    TFE_DATABASE_PARAMETERS: sslmode=disable
    TFE_OBJECT_STORAGE_TYPE: s3
    TFE_OBJECT_STORAGE_S3_BUCKET: ${s3_bucket}
    TFE_OBJECT_STORAGE_S3_REGION: ${region}
    TFE_OBJECT_STORAGE_S3_USE_INSTANCE_PROFILE: "true"
    TFE_REDIS_HOST: ${redis_host}
    TFE_REDIS_USE_AUTH: "false"
    TFE_IACT_SUBNETS: 0.0.0.0/0
  secrets:
    TFE_DATABASE_PASSWORD: ${pg_password}
    TFE_ENCRYPTION_PASSWORD: ${enc_password}
    TFE_OBJECT_STORAGE_S3_SERVER_SIDE_ENCRYPTION: AES256
    TFE_LICENSE: ${tfe_license}